export { default as Navigation } from "./Navigation";
export { default as Home } from "./Home";
export { default as Players } from "./Players";
export { default as MalePlayers } from "./MalePlayers";
export { default as FemalePlayers } from "./FemalePlayers";
export { default as Tournaments } from "./Tournaments";
export { default as Prizes } from "./Prizes";
export { default as Ratings } from "./Ratings";
export { default as Contact } from "./Contact";